In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from gflownet.gflownet import GFlowNet
from policy import ForwardPolicy, BackwardPolicy
from setGenerationEnv import SetGenerationEnv
from gflownet.utils import trajectory_balance_loss
from torch.optim import Adam
from tqdm import tqdm
import torch 

In [81]:
bcz_size = 2
size = 4
nActions = 4
setEnv = SetGenerationEnv(size, nActions)

s0 = torch.zeros(bcz_size, size).float()
curr0 = torch.tensor([1.0, 0.0])
actions = torch.tensor([2, 3])

s, curr = setEnv.update(s0, curr0, actions)
print(s)
print(curr)

tensor([[0., 3., 0., 0.],
        [4., 0., 0., 0.]])
tensor([1., 0.])


In [83]:
s[0][0] = 1
s[0][3] = 3
curr[0] = 2
print(s)
print(curr)

setEnv.mask(s, curr)

tensor([[1., 3., 0., 3.],
        [4., 0., 0., 0.]])
tensor([2., 0.])


tensor([[1., 1., 1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.]])

In [52]:
backward_policy = BackwardPolicy(setEnv.state_dim, num_actions=setEnv.num_actions)
backward_policy(s, curr)

tensor([[0.0000, 0.0000, 0.3333, 0.0000, 0.3333, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5000, 0.0000, 0.0000]])

In [53]:
forward_policy = ForwardPolicy(setEnv.state_dim, hidden_dim=32, num_actions=setEnv.num_actions)
forward_policy(s)

tensor([[0.0813, 0.2297, 0.1632, 0.1131, 0.0895, 0.1325, 0.1906],
        [0.1441, 0.1092, 0.1049, 0.0915, 0.0854, 0.2831, 0.1819]],
       grad_fn=<SoftmaxBackward0>)