In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from gflownet.gflownet import GFlowNet
from policy import ForwardPolicy, BackwardPolicy
from setGenerationEnv import SetGenerationEnv
from gflownet.utils import trajectory_balance_loss
from torch.optim import Adam
from tqdm import tqdm
import torch 

In [24]:
bcz_size = 2
size = 4
nActions = 4
setEnv = SetGenerationEnv(size, nActions)

s0 = torch.zeros(bcz_size, size).float()
curr0 = torch.tensor([1.0, 0.0])
actions = torch.tensor([2, 3])

s, curr = setEnv.update(s0, curr0, actions)
print(s)
print(curr)

tensor([[0., 3., 0., 0.],
        [4., 0., 0., 0.]])
tensor([1., 0.])


In [25]:
setEnv.mask(s, curr)

tensor([[0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 1., 0.]])

tensor([ 9.0100, 16.0100])

tensor([[0., 3., 0., 0.],
        [4., 0., 0., 0.]])